### ISSUE TITLE
Process stops on Google Ads - Terms of Service

### ISSUE THREAD

**Issue by martinratinaud** [ambanum/OpenTermsArchive#681]
With error in logs

```
0|cgus     | 2021-11-12 09:58:05 error Google Ads — Terms of Service                           FetchError: request to https://payments.google.com/payments/apis-secure/get_legal_document?ldi=31472 failed, reason: connect ECONNREFUSED 173.194.76.92:443
0|cgus     |     at ClientRequest.<anonymous> (file:///home/debian/cgus/node_modules/node-fetch/src/index.js:94:11)
0|cgus     |     at ClientRequest.emit (events.js:400:28)
0|cgus     |     at TLSSocket.socketErrorListener (_http_client.js:475:9)
0|cgus     |     at TLSSocket.emit (events.js:400:28)
0|cgus     |     at emitErrorNT (internal/streams/destroy.js:106:8)
0|cgus     |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
0|cgus     |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
0|cgus     | 2021-11-12 09:58:05 error                                                         unhandledRejection: request to https://payments.google.com/payments/apis-secure/get_legal_document?ldi=31472 failed, reason: connect ECONNREFUSED 173.194.76.92:443
0|cgus     | FetchError: request to https://payments.google.com/payments/apis-secure/get_legal_document?ldi=31472 failed, reason: connect ECONNREFUSED 173.194.76.92:443
0|cgus     |     at ClientRequest.<anonymous> (file:///home/debian/cgus/node_modules/node-fetch/src/index.js:94:11)
0|cgus     |     at ClientRequest.emit (events.js:400:28)
0|cgus     |     at TLSSocket.socketErrorListener (_http_client.js:475:9)
0|cgus     |     at TLSSocket.emit (events.js:400:28)
0|cgus     |     at emitErrorNT (internal/streams/destroy.js:106:8)
0|cgus     |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
0|cgus     |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
0|cgus     | 2021-11-12 09:58:05 error                                                         unhandledRejection FetchError: request to https://payments.google.com/payments/apis-secure/get_legal_document?ldi=31472 failed, reason: connect ECONNREFUSED 173.194.76.92:443
0|cgus     | 2021-11-12 09:58:05 error                                                         request to https://payments.google.com/payments/apis-secure/get_legal_document?ldi=31472 failed, reason: connect ECONNREFUSED 173.194.76.92:443
0|cgus     |
```

**Comment by MattiSG** [comment]
Fixed via #657.
