### ISSUE TITLE
unhandledRejection: Unexpected token 'export'

### ISSUE THREAD

**Issue by clementbiron** [ambanum/OpenTermsArchive#746]
I'm trying to use this filter

```javascript
export function removeUTMfromUrls(document) {
  const links = document.querySelectorAll("a");

  links.forEach((link) => {
    link.href = link.href.replace(/utm_[^=]*=[^&]*[&]{0,1}/g, "");
  });
}
```

in this declaration 
```json
{
  "name": "Google",
  "documents": {
    "Privacy Policy": {
      "fetch": "https://policies.google.com/privacy?hl=fr-FR&gl=FR",
      "select": "div[role=article]",
      "remove": ["img[src$='.svg']", "img[src^='data:image/svg+xml"],
      "filter": ["removeUTMfromUrls"]
    }
  }
}
```

and i get this error with `npm start "Google"`

```
 npm start "Google"

> open-terms-archive@0.15.0 start
> node --max-http-header-size=32768 src/index.js "Google"

(node:23844) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
2022-02-07 16:15:09 error                                                         unhandledRejection: Unexpected token 'export'
/Users/clementbiron/www/declarations-france/declarations/Google.filters.js:1
export function removeUTMfromUrls(document) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1025:15)
    at Module._compile (node:internal/modules/cjs/loader:1059:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:190:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async file:///Users/clementbiron/www/OpenTermsArchive/src/archivist/services/index.js:46:32
    at async Promise.all (index 0)
    at async file:///Users/clementbiron/www/OpenTermsArchive/src/archivist/services/index.js:32:5
    at async Promise.all (index 3)
    at async Module.load (file:///Users/clementbiron/www/OpenTermsArchive/src/archivist/services/index.js:21:3)
    at async Archivist.initialize (file:///Users/clementbiron/www/OpenTermsArchive/src/archivist/index.js:54:21)
    at async startOpenTermsArchive (file:///Users/clementbiron/www/OpenTermsArchive/src/index.js:35:3)
```

**Comment by clementbiron** [comment]
According to @Ndpnt, this [PR](https://github.com/OpenTermsArchive/declarations-france/pull/44) close this issue.
I suggest to document the addition and configuration of the package.json file of a subset.
