### ISSUE TITLE
Email notifications are sent without vault key

### ISSUE THREAD

**Issue by MattiSG** [ambanum/OpenTermsArchive#838]
We received this error over email:

```
2022-04-07 15:57:48 [31merror[39m unhandledRejection: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

at onClose (/home/vagrant/ota/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
at ChildProcess. (/home/vagrant/ota/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:195:85)
at ChildProcess.emit (events.js:400:28)
at Process.ChildProcess._handle.onexit (internal/child_process.js:280:12)
at onErrorNT (internal/child_process.js:469:16)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

…but the person who generated it did not have access to the vault key. This is a sign of a security problem.

**Comment by MattiSG** [comment]
Cannot reproduce.
